version: '3.8'

services:
  backend:
    build: ./backend
    container_name: codeblock-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - codeblock-net

  frontend:
    build: ./frontend
    container_name: codeblock-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - codeblock-net

networks:
  codeblock-net:
    driver: bridge
