version: '3.8'

services:
  backend:
    image: sharonsh99/codeblock-backend:latest
    container_name: codeblock-backend
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    image: sharonsh99/codeblock-frontend:latest
    container_name: codeblock-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
